### ISSUE TITLE
Jokenpo

### ISSUE THREAD

**Issue by PierreVieira** [Piknowledge/ExerciciosCSharp#5]
Fazer um programa em C# que jogue jogo da velha com o usuário. Com os seguintes requesitos:
- Fazer com que o computador gere um número aleatório para representar pedra, papel ou tesoura.
- Mostrar qual foi a escolha do computador
- Pedir para que o usuário entre com um número que representa pedra, papel ou tesoura
- Se o usuário informa um número que não representa pedra papel ou tesoura o programa deve exibir uma mensagem de erro e encerrar.
- Mostrar resultado (empate, vitória ou derrota)

**Comment by Vickymayte** [comment]
## Qual é o problema? 
Fazer um programa em c# mostrando o jogo da velha. 

## Solução
Ver codigo anexo. 

---
Issue Closed 
@PierreVieira  #5
